// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutPageDocumentDataSlicesSlice =
  | CoreValuesSlice
  | LongTermGoalsSlice
  | TheVisionSlice
  | BlockchainAndAiBenefitsSlice
  | ChallengesSlice
  | TbkFoundationBackgroundSlice
  | AboutTbkFoundationSlice;

/**
 * Content for AboutPage documents
 */
interface AboutPageDocumentData {
  /**
   * Slice Zone field in *AboutPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice> /**
   * Meta Title field in *AboutPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *AboutPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *AboutPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * AboutPage document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | SliceInifitySlice
  | VerticalStepsSlice
  | TopExchangeSlice
  | MenuWhitePaperSlice
  | SliderTokenSlice
  | TableMultiTiredSlice
  | FlowEarnMobileCompoSlice
  | HomeCtaMobileSlice
  | TitleComplexSlice
  | StepApplySlice
  | TableEarnSlice
  | LinkSlice
  | FlowEarnSlice
  | EarnSlice
  | TitleMenuStartSlice
  | BackgroundSlice
  | ReadyToTransformSlice
  | TextSlice
  | CollapseAskedAnsweredSlice
  | TableMembershipPerksSlice
  | TextDogBlueSlice
  | IconSlice
  | CardSynergySlice
  | CardInitialListingPriceSlice
  | CardTotalSupplySlice
  | PieChartSlice
  | ButtonSlice
  | TitleHeaderGradientSlice
  | NumberStatisticSlice
  | TitleCardSlice
  | TitleHeaderSlice
  | ImageSlice
  | DiscriptionSlice
  | BannerVideoSlice
  | TbkIdentifyGiftSlice
  | TbkIdentifyReferralSlice
  | TbkIdentifyAbassadorSlice
  | TbkIdentifySlice
  | TokenWhitepaperSlice
  | SustainabilityInitiativesSlice
  | CoreTechnologySlice
  | TestBox2Slice
  | TestBox1Slice
  | PaymentEcosystemSlice
  | TbkSmartProgramSlice
  | TbkTokenEcosystemSlice
  | CardServicesSlice
  | LongTermGoalsSlice
  | TbkFoundationBackgroundSlice
  | TheVisionSlice
  | CoreValuesSlice
  | ChallengesSlice
  | BlockchainAndAiBenefitsSlice
  | AboutTbkFoundationSlice
  | CtaSlice
  | TitleAskAndAnswerSlice
  | CollapeGroupAskAndAnswerSlice
  | JoinOutCommunitySlice
  | ServiceSlice
  | TitleMembershipSlice
  | TableMembershipSlice
  | TitleMultichainSlice
  | CardGroupMultichainSlice
  | TitlePaymentEcosystemSlice
  | CardGroupPaymentEcosystemSlice
  | TitleConnectingSlice
  | CardGroupConnectingSlice
  | TitleBenefitsSlice
  | ImgBgBenefitsSlice
  | CardGroupBenefitsSlice
  | TitleCoreFunctionsSlice
  | CardGroupCoreFunctionsSlice
  | TitleSmartProgramSlice
  | ImgBgSmartProgramSlice
  | ContentSmartProgramSlice
  | BtnReadmoreSlice
  | TitleSynergySlice
  | ImgBgSynergySlice
  | CardGroupSynergySlice
  | ImageEndGridSlice
  | ImageStartGridSlice
  | TitleTokenUtilitySlice
  | ImgBgTokenUtilitySlice
  | CardGroupTokenUtilitySlice
  | TitleCoreEcosystemSlice
  | CardGroupCoreEcosytemSlice
  | TbkEcosystemSlice
  | ExchangesSlice
  | TitleTokenomicsSlice
  | PieChartTokenomicsSlice
  | OverviewTokenomicsSlice
  | CardTokenomicsSlice
  | FunctionsSlice
  | MonacoSlice
  | VisionCardSlice
  | IntroductionSlice
  | MissionCardSlice
  | PurposeCardSlice
  | CardStatisticSlice
  | BannerIntroSlice
  | BannerAboutSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = AboutPageDocument | PageDocument;

/**
 * Default variation for AboutTbkFoundation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTbkFoundationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *AboutTbkFoundation*
 */
type AboutTbkFoundationSliceVariation = AboutTbkFoundationSliceDefault;

/**
 * AboutTbkFoundation Shared Slice
 *
 * - **API ID**: `about_tbk_foundation`
 * - **Description**: AboutTbkFoundation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTbkFoundationSlice = prismic.SharedSlice<
  "about_tbk_foundation",
  AboutTbkFoundationSliceVariation
>;

/**
 * Default variation for Background Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Background*
 */
type BackgroundSliceVariation = BackgroundSliceDefault;

/**
 * Background Shared Slice
 *
 * - **API ID**: `background`
 * - **Description**: Background
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BackgroundSlice = prismic.SharedSlice<
  "background",
  BackgroundSliceVariation
>;

/**
 * Default variation for BannerAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BannerAbout*
 */
type BannerAboutSliceVariation = BannerAboutSliceDefault;

/**
 * BannerAbout Shared Slice
 *
 * - **API ID**: `banner_about`
 * - **Description**: BannerAbout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerAboutSlice = prismic.SharedSlice<
  "banner_about",
  BannerAboutSliceVariation
>;

/**
 * Default variation for BannerIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BannerIntro*
 */
type BannerIntroSliceVariation = BannerIntroSliceDefault;

/**
 * BannerIntro Shared Slice
 *
 * - **API ID**: `banner_intro`
 * - **Description**: BannerIntro
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerIntroSlice = prismic.SharedSlice<
  "banner_intro",
  BannerIntroSliceVariation
>;

/**
 * Default variation for BannerVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BannerVideo*
 */
type BannerVideoSliceVariation = BannerVideoSliceDefault;

/**
 * BannerVideo Shared Slice
 *
 * - **API ID**: `banner_video`
 * - **Description**: BannerVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerVideoSlice = prismic.SharedSlice<
  "banner_video",
  BannerVideoSliceVariation
>;

/**
 * Default variation for BlockchainAndAiBenefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockchainAndAiBenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BlockchainAndAiBenefits*
 */
type BlockchainAndAiBenefitsSliceVariation =
  BlockchainAndAiBenefitsSliceDefault;

/**
 * BlockchainAndAiBenefits Shared Slice
 *
 * - **API ID**: `blockchain_and_ai_benefits`
 * - **Description**: BlockchainAndAiBenefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockchainAndAiBenefitsSlice = prismic.SharedSlice<
  "blockchain_and_ai_benefits",
  BlockchainAndAiBenefitsSliceVariation
>;

/**
 * Default variation for BtnReadmore Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BtnReadmoreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BtnReadmore*
 */
type BtnReadmoreSliceVariation = BtnReadmoreSliceDefault;

/**
 * BtnReadmore Shared Slice
 *
 * - **API ID**: `btn_readmore`
 * - **Description**: BtnReadmore
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BtnReadmoreSlice = prismic.SharedSlice<
  "btn_readmore",
  BtnReadmoreSliceVariation
>;

/**
 * Default variation for Button Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Button*
 */
type ButtonSliceVariation = ButtonSliceDefault;

/**
 * Button Shared Slice
 *
 * - **API ID**: `button`
 * - **Description**: Button
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ButtonSlice = prismic.SharedSlice<"button", ButtonSliceVariation>;

/**
 * Default variation for CardGroupBenefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupBenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardGroupBenefits*
 */
type CardGroupBenefitsSliceVariation = CardGroupBenefitsSliceDefault;

/**
 * CardGroupBenefits Shared Slice
 *
 * - **API ID**: `card_group_benefits`
 * - **Description**: CardGroupBenefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupBenefitsSlice = prismic.SharedSlice<
  "card_group_benefits",
  CardGroupBenefitsSliceVariation
>;

/**
 * Default variation for CardGroupConnecting Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupConnectingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardGroupConnecting*
 */
type CardGroupConnectingSliceVariation = CardGroupConnectingSliceDefault;

/**
 * CardGroupConnecting Shared Slice
 *
 * - **API ID**: `card_group_connecting`
 * - **Description**: CardGroupConnecting
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupConnectingSlice = prismic.SharedSlice<
  "card_group_connecting",
  CardGroupConnectingSliceVariation
>;

/**
 * Default variation for CardGroupCoreEcosytem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupCoreEcosytemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardGroupCoreEcosytem*
 */
type CardGroupCoreEcosytemSliceVariation = CardGroupCoreEcosytemSliceDefault;

/**
 * CardGroupCoreEcosytem Shared Slice
 *
 * - **API ID**: `card_group_core_ecosytem`
 * - **Description**: CardGroupCoreEcosytem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupCoreEcosytemSlice = prismic.SharedSlice<
  "card_group_core_ecosytem",
  CardGroupCoreEcosytemSliceVariation
>;

/**
 * Default variation for CardGroupCoreFunctions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupCoreFunctionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardGroupCoreFunctions*
 */
type CardGroupCoreFunctionsSliceVariation = CardGroupCoreFunctionsSliceDefault;

/**
 * CardGroupCoreFunctions Shared Slice
 *
 * - **API ID**: `card_group_core_functions`
 * - **Description**: CardGroupCoreFunctions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupCoreFunctionsSlice = prismic.SharedSlice<
  "card_group_core_functions",
  CardGroupCoreFunctionsSliceVariation
>;

/**
 * Default variation for CardGroupMultichain Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupMultichainSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardGroupMultichain*
 */
type CardGroupMultichainSliceVariation = CardGroupMultichainSliceDefault;

/**
 * CardGroupMultichain Shared Slice
 *
 * - **API ID**: `card_group_multichain`
 * - **Description**: CardGroupMultichain
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupMultichainSlice = prismic.SharedSlice<
  "card_group_multichain",
  CardGroupMultichainSliceVariation
>;

/**
 * Default variation for CardGroupPaymentEcosystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupPaymentEcosystemSliceDefault =
  prismic.SharedSliceVariation<"default", Record<string, never>, never>;

/**
 * Slice variation for *CardGroupPaymentEcosystem*
 */
type CardGroupPaymentEcosystemSliceVariation =
  CardGroupPaymentEcosystemSliceDefault;

/**
 * CardGroupPaymentEcosystem Shared Slice
 *
 * - **API ID**: `card_group_payment_ecosystem`
 * - **Description**: CardGroupPaymentEcosystem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupPaymentEcosystemSlice = prismic.SharedSlice<
  "card_group_payment_ecosystem",
  CardGroupPaymentEcosystemSliceVariation
>;

/**
 * Default variation for CardGroupSynergy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupSynergySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardGroupSynergy*
 */
type CardGroupSynergySliceVariation = CardGroupSynergySliceDefault;

/**
 * CardGroupSynergy Shared Slice
 *
 * - **API ID**: `card_group_synergy`
 * - **Description**: CardGroupSynergy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupSynergySlice = prismic.SharedSlice<
  "card_group_synergy",
  CardGroupSynergySliceVariation
>;

/**
 * Default variation for CardGroupTokenUtility Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupTokenUtilitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardGroupTokenUtility*
 */
type CardGroupTokenUtilitySliceVariation = CardGroupTokenUtilitySliceDefault;

/**
 * CardGroupTokenUtility Shared Slice
 *
 * - **API ID**: `card_group_token_utility`
 * - **Description**: CardGroupTokenUtility
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGroupTokenUtilitySlice = prismic.SharedSlice<
  "card_group_token_utility",
  CardGroupTokenUtilitySliceVariation
>;

/**
 * Default variation for CardInitialListingPrice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardInitialListingPriceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardInitialListingPrice*
 */
type CardInitialListingPriceSliceVariation =
  CardInitialListingPriceSliceDefault;

/**
 * CardInitialListingPrice Shared Slice
 *
 * - **API ID**: `card_initial_listing_price`
 * - **Description**: CardInitialListingPrice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardInitialListingPriceSlice = prismic.SharedSlice<
  "card_initial_listing_price",
  CardInitialListingPriceSliceVariation
>;

/**
 * Default variation for CardServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardServices*
 */
type CardServicesSliceVariation = CardServicesSliceDefault;

/**
 * CardServices Shared Slice
 *
 * - **API ID**: `card_services`
 * - **Description**: CardServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardServicesSlice = prismic.SharedSlice<
  "card_services",
  CardServicesSliceVariation
>;

/**
 * Default variation for CardStatistic Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardStatisticSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardStatistic*
 */
type CardStatisticSliceVariation = CardStatisticSliceDefault;

/**
 * CardStatistic Shared Slice
 *
 * - **API ID**: `card_statistic`
 * - **Description**: CardStatistic
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardStatisticSlice = prismic.SharedSlice<
  "card_statistic",
  CardStatisticSliceVariation
>;

/**
 * Default variation for CardSynergy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSynergySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardSynergy*
 */
type CardSynergySliceVariation = CardSynergySliceDefault;

/**
 * CardSynergy Shared Slice
 *
 * - **API ID**: `card_synergy`
 * - **Description**: CardSynergy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardSynergySlice = prismic.SharedSlice<
  "card_synergy",
  CardSynergySliceVariation
>;

/**
 * Default variation for CardTokenomics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardTokenomicsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardTokenomics*
 */
type CardTokenomicsSliceVariation = CardTokenomicsSliceDefault;

/**
 * CardTokenomics Shared Slice
 *
 * - **API ID**: `card_tokenomics`
 * - **Description**: CardTokenomics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardTokenomicsSlice = prismic.SharedSlice<
  "card_tokenomics",
  CardTokenomicsSliceVariation
>;

/**
 * Default variation for CardTotalSupply Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardTotalSupplySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CardTotalSupply*
 */
type CardTotalSupplySliceVariation = CardTotalSupplySliceDefault;

/**
 * CardTotalSupply Shared Slice
 *
 * - **API ID**: `card_total_supply`
 * - **Description**: CardTotalSupply
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardTotalSupplySlice = prismic.SharedSlice<
  "card_total_supply",
  CardTotalSupplySliceVariation
>;

/**
 * Default variation for Challenges Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChallengesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Challenges*
 */
type ChallengesSliceVariation = ChallengesSliceDefault;

/**
 * Challenges Shared Slice
 *
 * - **API ID**: `challenges`
 * - **Description**: Challenges
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChallengesSlice = prismic.SharedSlice<
  "challenges",
  ChallengesSliceVariation
>;

/**
 * Default variation for CollapeGroupAskAndAnswer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapeGroupAskAndAnswerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CollapeGroupAskAndAnswer*
 */
type CollapeGroupAskAndAnswerSliceVariation =
  CollapeGroupAskAndAnswerSliceDefault;

/**
 * CollapeGroupAskAndAnswer Shared Slice
 *
 * - **API ID**: `collape_group_ask_and_answer`
 * - **Description**: CollapeGroupAskAndAnswer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapeGroupAskAndAnswerSlice = prismic.SharedSlice<
  "collape_group_ask_and_answer",
  CollapeGroupAskAndAnswerSliceVariation
>;

/**
 * Default variation for CollapseAskedAnswered Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapseAskedAnsweredSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CollapseAskedAnswered*
 */
type CollapseAskedAnsweredSliceVariation = CollapseAskedAnsweredSliceDefault;

/**
 * CollapseAskedAnswered Shared Slice
 *
 * - **API ID**: `collapse_asked_answered`
 * - **Description**: CollapseAskedAnswered
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollapseAskedAnsweredSlice = prismic.SharedSlice<
  "collapse_asked_answered",
  CollapseAskedAnsweredSliceVariation
>;

/**
 * Default variation for ContentSmartProgram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSmartProgramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContentSmartProgram*
 */
type ContentSmartProgramSliceVariation = ContentSmartProgramSliceDefault;

/**
 * ContentSmartProgram Shared Slice
 *
 * - **API ID**: `content_smart_program`
 * - **Description**: ContentSmartProgram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSmartProgramSlice = prismic.SharedSlice<
  "content_smart_program",
  ContentSmartProgramSliceVariation
>;

/**
 * Default variation for CoreTechnology Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreTechnologySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CoreTechnology*
 */
type CoreTechnologySliceVariation = CoreTechnologySliceDefault;

/**
 * CoreTechnology Shared Slice
 *
 * - **API ID**: `core_technology`
 * - **Description**: CoreTechnology
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreTechnologySlice = prismic.SharedSlice<
  "core_technology",
  CoreTechnologySliceVariation
>;

/**
 * Default variation for CoreValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CoreValues*
 */
type CoreValuesSliceVariation = CoreValuesSliceDefault;

/**
 * CoreValues Shared Slice
 *
 * - **API ID**: `core_values`
 * - **Description**: CoreValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoreValuesSlice = prismic.SharedSlice<
  "core_values",
  CoreValuesSliceVariation
>;

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Default variation for Discription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Discription*
 */
type DiscriptionSliceVariation = DiscriptionSliceDefault;

/**
 * Discription Shared Slice
 *
 * - **API ID**: `discription`
 * - **Description**: Discription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscriptionSlice = prismic.SharedSlice<
  "discription",
  DiscriptionSliceVariation
>;

/**
 * Default variation for Earn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EarnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Earn*
 */
type EarnSliceVariation = EarnSliceDefault;

/**
 * Earn Shared Slice
 *
 * - **API ID**: `earn`
 * - **Description**: Earn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EarnSlice = prismic.SharedSlice<"earn", EarnSliceVariation>;

/**
 * Default variation for Exchanges Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExchangesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Exchanges*
 */
type ExchangesSliceVariation = ExchangesSliceDefault;

/**
 * Exchanges Shared Slice
 *
 * - **API ID**: `exchanges`
 * - **Description**: Exchanges
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExchangesSlice = prismic.SharedSlice<
  "exchanges",
  ExchangesSliceVariation
>;

/**
 * Default variation for FlowEarn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FlowEarnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FlowEarn*
 */
type FlowEarnSliceVariation = FlowEarnSliceDefault;

/**
 * FlowEarn Shared Slice
 *
 * - **API ID**: `flow_earn`
 * - **Description**: FlowEarn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FlowEarnSlice = prismic.SharedSlice<
  "flow_earn",
  FlowEarnSliceVariation
>;

/**
 * Default variation for FlowEarnMobileCompo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FlowEarnMobileCompoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FlowEarnMobileCompo*
 */
type FlowEarnMobileCompoSliceVariation = FlowEarnMobileCompoSliceDefault;

/**
 * FlowEarnMobileCompo Shared Slice
 *
 * - **API ID**: `flow_earn_mobile_compo`
 * - **Description**: FlowEarnMobileCompo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FlowEarnMobileCompoSlice = prismic.SharedSlice<
  "flow_earn_mobile_compo",
  FlowEarnMobileCompoSliceVariation
>;

/**
 * Default variation for Functions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FunctionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Functions*
 */
type FunctionsSliceVariation = FunctionsSliceDefault;

/**
 * Functions Shared Slice
 *
 * - **API ID**: `functions`
 * - **Description**: Functions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FunctionsSlice = prismic.SharedSlice<
  "functions",
  FunctionsSliceVariation
>;

/**
 * Default variation for HomeCtaMobile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCtaMobileSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HomeCtaMobile*
 */
type HomeCtaMobileSliceVariation = HomeCtaMobileSliceDefault;

/**
 * HomeCtaMobile Shared Slice
 *
 * - **API ID**: `home_cta_mobile`
 * - **Description**: HomeCtaMobile
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeCtaMobileSlice = prismic.SharedSlice<
  "home_cta_mobile",
  HomeCtaMobileSliceVariation
>;

/**
 * Default variation for Icon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Icon*
 */
type IconSliceVariation = IconSliceDefault;

/**
 * Icon Shared Slice
 *
 * - **API ID**: `icon`
 * - **Description**: Icon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconSlice = prismic.SharedSlice<"icon", IconSliceVariation>;

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Default variation for ImageEndGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageEndGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ImageEndGrid*
 */
type ImageEndGridSliceVariation = ImageEndGridSliceDefault;

/**
 * ImageEndGrid Shared Slice
 *
 * - **API ID**: `image_end_grid`
 * - **Description**: ImageEndGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageEndGridSlice = prismic.SharedSlice<
  "image_end_grid",
  ImageEndGridSliceVariation
>;

/**
 * Default variation for ImageStartGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageStartGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ImageStartGrid*
 */
type ImageStartGridSliceVariation = ImageStartGridSliceDefault;

/**
 * ImageStartGrid Shared Slice
 *
 * - **API ID**: `image_start_grid`
 * - **Description**: ImageStartGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageStartGridSlice = prismic.SharedSlice<
  "image_start_grid",
  ImageStartGridSliceVariation
>;

/**
 * Default variation for ImgBgBenefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgBenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ImgBgBenefits*
 */
type ImgBgBenefitsSliceVariation = ImgBgBenefitsSliceDefault;

/**
 * ImgBgBenefits Shared Slice
 *
 * - **API ID**: `img_bg_benefits`
 * - **Description**: ImgBgBenefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgBenefitsSlice = prismic.SharedSlice<
  "img_bg_benefits",
  ImgBgBenefitsSliceVariation
>;

/**
 * Default variation for ImgBgSmartProgram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgSmartProgramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ImgBgSmartProgram*
 */
type ImgBgSmartProgramSliceVariation = ImgBgSmartProgramSliceDefault;

/**
 * ImgBgSmartProgram Shared Slice
 *
 * - **API ID**: `img_bg_smart_program`
 * - **Description**: ImgBgSmartProgram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgSmartProgramSlice = prismic.SharedSlice<
  "img_bg_smart_program",
  ImgBgSmartProgramSliceVariation
>;

/**
 * Default variation for ImgBgSynergy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgSynergySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ImgBgSynergy*
 */
type ImgBgSynergySliceVariation = ImgBgSynergySliceDefault;

/**
 * ImgBgSynergy Shared Slice
 *
 * - **API ID**: `img_bg_synergy`
 * - **Description**: ImgBgSynergy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgSynergySlice = prismic.SharedSlice<
  "img_bg_synergy",
  ImgBgSynergySliceVariation
>;

/**
 * Default variation for ImgBgTokenUtility Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgTokenUtilitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ImgBgTokenUtility*
 */
type ImgBgTokenUtilitySliceVariation = ImgBgTokenUtilitySliceDefault;

/**
 * ImgBgTokenUtility Shared Slice
 *
 * - **API ID**: `img_bg_token_utility`
 * - **Description**: ImgBgTokenUtility
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImgBgTokenUtilitySlice = prismic.SharedSlice<
  "img_bg_token_utility",
  ImgBgTokenUtilitySliceVariation
>;

/**
 * Default variation for Introduction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Introduction*
 */
type IntroductionSliceVariation = IntroductionSliceDefault;

/**
 * Introduction Shared Slice
 *
 * - **API ID**: `introduction`
 * - **Description**: Introduction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSlice = prismic.SharedSlice<
  "introduction",
  IntroductionSliceVariation
>;

/**
 * Default variation for JoinOutCommunity Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinOutCommunitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *JoinOutCommunity*
 */
type JoinOutCommunitySliceVariation = JoinOutCommunitySliceDefault;

/**
 * JoinOutCommunity Shared Slice
 *
 * - **API ID**: `join_out_community`
 * - **Description**: JoinOutCommunity
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinOutCommunitySlice = prismic.SharedSlice<
  "join_out_community",
  JoinOutCommunitySliceVariation
>;

/**
 * Default variation for Link Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Link*
 */
type LinkSliceVariation = LinkSliceDefault;

/**
 * Link Shared Slice
 *
 * - **API ID**: `link`
 * - **Description**: Link
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSlice = prismic.SharedSlice<"link", LinkSliceVariation>;

/**
 * Default variation for LongTermGoals Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LongTermGoalsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *LongTermGoals*
 */
type LongTermGoalsSliceVariation = LongTermGoalsSliceDefault;

/**
 * LongTermGoals Shared Slice
 *
 * - **API ID**: `long_term_goals`
 * - **Description**: LongTermGoals
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LongTermGoalsSlice = prismic.SharedSlice<
  "long_term_goals",
  LongTermGoalsSliceVariation
>;

/**
 * Default variation for MenuWhitePaper Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuWhitePaperSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *MenuWhitePaper*
 */
type MenuWhitePaperSliceVariation = MenuWhitePaperSliceDefault;

/**
 * MenuWhitePaper Shared Slice
 *
 * - **API ID**: `menu_white_paper`
 * - **Description**: MenuWhitePaper
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuWhitePaperSlice = prismic.SharedSlice<
  "menu_white_paper",
  MenuWhitePaperSliceVariation
>;

/**
 * Default variation for MissionCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *MissionCard*
 */
type MissionCardSliceVariation = MissionCardSliceDefault;

/**
 * MissionCard Shared Slice
 *
 * - **API ID**: `mission_card`
 * - **Description**: MissionCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionCardSlice = prismic.SharedSlice<
  "mission_card",
  MissionCardSliceVariation
>;

/**
 * Default variation for Monaco Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MonacoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Monaco*
 */
type MonacoSliceVariation = MonacoSliceDefault;

/**
 * Monaco Shared Slice
 *
 * - **API ID**: `monaco`
 * - **Description**: Monaco
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MonacoSlice = prismic.SharedSlice<"monaco", MonacoSliceVariation>;

/**
 * Default variation for NumberStatistic Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumberStatisticSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *NumberStatistic*
 */
type NumberStatisticSliceVariation = NumberStatisticSliceDefault;

/**
 * NumberStatistic Shared Slice
 *
 * - **API ID**: `number_statistic`
 * - **Description**: NumberStatistic
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumberStatisticSlice = prismic.SharedSlice<
  "number_statistic",
  NumberStatisticSliceVariation
>;

/**
 * Default variation for OverviewTokenomics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OverviewTokenomicsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *OverviewTokenomics*
 */
type OverviewTokenomicsSliceVariation = OverviewTokenomicsSliceDefault;

/**
 * OverviewTokenomics Shared Slice
 *
 * - **API ID**: `overview_tokenomics`
 * - **Description**: OverviewTokenomics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OverviewTokenomicsSlice = prismic.SharedSlice<
  "overview_tokenomics",
  OverviewTokenomicsSliceVariation
>;

/**
 * Default variation for PaymentEcosystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentEcosystemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *PaymentEcosystem*
 */
type PaymentEcosystemSliceVariation = PaymentEcosystemSliceDefault;

/**
 * PaymentEcosystem Shared Slice
 *
 * - **API ID**: `payment_ecosystem`
 * - **Description**: PaymentEcosystem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentEcosystemSlice = prismic.SharedSlice<
  "payment_ecosystem",
  PaymentEcosystemSliceVariation
>;

/**
 * Default variation for PieChart Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PieChartSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *PieChart*
 */
type PieChartSliceVariation = PieChartSliceDefault;

/**
 * PieChart Shared Slice
 *
 * - **API ID**: `pie_chart`
 * - **Description**: PieChart
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PieChartSlice = prismic.SharedSlice<
  "pie_chart",
  PieChartSliceVariation
>;

/**
 * Default variation for PieChartTokenomics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PieChartTokenomicsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *PieChartTokenomics*
 */
type PieChartTokenomicsSliceVariation = PieChartTokenomicsSliceDefault;

/**
 * PieChartTokenomics Shared Slice
 *
 * - **API ID**: `pie_chart_tokenomics`
 * - **Description**: PieChartTokenomics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PieChartTokenomicsSlice = prismic.SharedSlice<
  "pie_chart_tokenomics",
  PieChartTokenomicsSliceVariation
>;

/**
 * Default variation for PurposeCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PurposeCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *PurposeCard*
 */
type PurposeCardSliceVariation = PurposeCardSliceDefault;

/**
 * PurposeCard Shared Slice
 *
 * - **API ID**: `purpose_card`
 * - **Description**: PurposeCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PurposeCardSlice = prismic.SharedSlice<
  "purpose_card",
  PurposeCardSliceVariation
>;

/**
 * Default variation for ReadyToTransform Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReadyToTransformSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ReadyToTransform*
 */
type ReadyToTransformSliceVariation = ReadyToTransformSliceDefault;

/**
 * ReadyToTransform Shared Slice
 *
 * - **API ID**: `ready_to_transform`
 * - **Description**: ReadyToTransform
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReadyToTransformSlice = prismic.SharedSlice<
  "ready_to_transform",
  ReadyToTransformSliceVariation
>;

/**
 * Default variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Service*
 */
type ServiceSliceVariation = ServiceSliceDefault;

/**
 * Service Shared Slice
 *
 * - **API ID**: `service`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSlice = prismic.SharedSlice<
  "service",
  ServiceSliceVariation
>;

/**
 * Default variation for SliceInifity Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliceInifitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SliceInifity*
 */
type SliceInifitySliceVariation = SliceInifitySliceDefault;

/**
 * SliceInifity Shared Slice
 *
 * - **API ID**: `slice_inifity`
 * - **Description**: SliceInifity
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliceInifitySlice = prismic.SharedSlice<
  "slice_inifity",
  SliceInifitySliceVariation
>;

/**
 * Default variation for SliderToken Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderTokenSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SliderToken*
 */
type SliderTokenSliceVariation = SliderTokenSliceDefault;

/**
 * SliderToken Shared Slice
 *
 * - **API ID**: `slider_token`
 * - **Description**: SliderToken
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderTokenSlice = prismic.SharedSlice<
  "slider_token",
  SliderTokenSliceVariation
>;

/**
 * Default variation for StepApply Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepApplySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *StepApply*
 */
type StepApplySliceVariation = StepApplySliceDefault;

/**
 * StepApply Shared Slice
 *
 * - **API ID**: `step_apply`
 * - **Description**: StepApply
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepApplySlice = prismic.SharedSlice<
  "step_apply",
  StepApplySliceVariation
>;

/**
 * Default variation for SustainabilityInitiatives Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SustainabilityInitiativesSliceDefault =
  prismic.SharedSliceVariation<"default", Record<string, never>, never>;

/**
 * Slice variation for *SustainabilityInitiatives*
 */
type SustainabilityInitiativesSliceVariation =
  SustainabilityInitiativesSliceDefault;

/**
 * SustainabilityInitiatives Shared Slice
 *
 * - **API ID**: `sustainability_initiatives`
 * - **Description**: SustainabilityInitiatives
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SustainabilityInitiativesSlice = prismic.SharedSlice<
  "sustainability_initiatives",
  SustainabilityInitiativesSliceVariation
>;

/**
 * Default variation for TableEarn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableEarnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TableEarn*
 */
type TableEarnSliceVariation = TableEarnSliceDefault;

/**
 * TableEarn Shared Slice
 *
 * - **API ID**: `table_earn`
 * - **Description**: TableEarn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableEarnSlice = prismic.SharedSlice<
  "table_earn",
  TableEarnSliceVariation
>;

/**
 * Default variation for TableMembership Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableMembershipSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TableMembership*
 */
type TableMembershipSliceVariation = TableMembershipSliceDefault;

/**
 * TableMembership Shared Slice
 *
 * - **API ID**: `table_membership`
 * - **Description**: TableMembership
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableMembershipSlice = prismic.SharedSlice<
  "table_membership",
  TableMembershipSliceVariation
>;

/**
 * Default variation for TableMembershipPerks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableMembershipPerksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TableMembershipPerks*
 */
type TableMembershipPerksSliceVariation = TableMembershipPerksSliceDefault;

/**
 * TableMembershipPerks Shared Slice
 *
 * - **API ID**: `table_membership_perks`
 * - **Description**: TableMembershipPerks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableMembershipPerksSlice = prismic.SharedSlice<
  "table_membership_perks",
  TableMembershipPerksSliceVariation
>;

/**
 * Default variation for TableMultiTired Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableMultiTiredSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TableMultiTired*
 */
type TableMultiTiredSliceVariation = TableMultiTiredSliceDefault;

/**
 * TableMultiTired Shared Slice
 *
 * - **API ID**: `table_multi_tired`
 * - **Description**: TableMultiTired
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableMultiTiredSlice = prismic.SharedSlice<
  "table_multi_tired",
  TableMultiTiredSliceVariation
>;

/**
 * Default variation for TbkEcosystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkEcosystemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkEcosystem*
 */
type TbkEcosystemSliceVariation = TbkEcosystemSliceDefault;

/**
 * TbkEcosystem Shared Slice
 *
 * - **API ID**: `tbk_ecosystem`
 * - **Description**: TbkEcosystem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkEcosystemSlice = prismic.SharedSlice<
  "tbk_ecosystem",
  TbkEcosystemSliceVariation
>;

/**
 * Default variation for TbkFoundationBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkFoundationBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkFoundationBackground*
 */
type TbkFoundationBackgroundSliceVariation =
  TbkFoundationBackgroundSliceDefault;

/**
 * TbkFoundationBackground Shared Slice
 *
 * - **API ID**: `tbk_foundation_background`
 * - **Description**: TbkFoundationBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkFoundationBackgroundSlice = prismic.SharedSlice<
  "tbk_foundation_background",
  TbkFoundationBackgroundSliceVariation
>;

/**
 * Default variation for TbkInfinity Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkInfinity*
 */
type TbkIdentifySliceVariation = TbkIdentifySliceDefault;

/**
 * TbkInfinity Shared Slice
 *
 * - **API ID**: `tbk_identify`
 * - **Description**: TbkIdentify
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifySlice = prismic.SharedSlice<
  "tbk_identify",
  TbkIdentifySliceVariation
>;

/**
 * Default variation for TbkInfinityAbassador Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifyAbassadorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkInfinityAbassador*
 */
type TbkIdentifyAbassadorSliceVariation = TbkIdentifyAbassadorSliceDefault;

/**
 * TbkInfinityAbassador Shared Slice
 *
 * - **API ID**: `tbk_identify_abassador`
 * - **Description**: TbkIdentifyAbassador
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifyAbassadorSlice = prismic.SharedSlice<
  "tbk_identify_abassador",
  TbkIdentifyAbassadorSliceVariation
>;

/**
 * Default variation for TbkInfinityGift Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifyGiftSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkInfinityGift*
 */
type TbkIdentifyGiftSliceVariation = TbkIdentifyGiftSliceDefault;

/**
 * TbkInfinityGift Shared Slice
 *
 * - **API ID**: `tbk_identify_gift`
 * - **Description**: TbkIdentifyGift
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifyGiftSlice = prismic.SharedSlice<
  "tbk_identify_gift",
  TbkIdentifyGiftSliceVariation
>;

/**
 * Default variation for TbkInfinityReferral Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifyReferralSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkInfinityReferral*
 */
type TbkIdentifyReferralSliceVariation = TbkIdentifyReferralSliceDefault;

/**
 * TbkInfinityReferral Shared Slice
 *
 * - **API ID**: `tbk_identify_referral`
 * - **Description**: TbkIdentifyReferral
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkIdentifyReferralSlice = prismic.SharedSlice<
  "tbk_identify_referral",
  TbkIdentifyReferralSliceVariation
>;

/**
 * Default variation for TbkSmartProgram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkSmartProgramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkSmartProgram*
 */
type TbkSmartProgramSliceVariation = TbkSmartProgramSliceDefault;

/**
 * TbkSmartProgram Shared Slice
 *
 * - **API ID**: `tbk_smart_program`
 * - **Description**: TbkSmartProgram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkSmartProgramSlice = prismic.SharedSlice<
  "tbk_smart_program",
  TbkSmartProgramSliceVariation
>;

/**
 * Default variation for TbkTokenEcosystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkTokenEcosystemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TbkTokenEcosystem*
 */
type TbkTokenEcosystemSliceVariation = TbkTokenEcosystemSliceDefault;

/**
 * TbkTokenEcosystem Shared Slice
 *
 * - **API ID**: `tbk_token_ecosystem`
 * - **Description**: TbkTokenEcosystem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TbkTokenEcosystemSlice = prismic.SharedSlice<
  "tbk_token_ecosystem",
  TbkTokenEcosystemSliceVariation
>;

/**
 * Default variation for TestBox1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestBox1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TestBox1*
 */
type TestBox1SliceVariation = TestBox1SliceDefault;

/**
 * TestBox1 Shared Slice
 *
 * - **API ID**: `test_box1`
 * - **Description**: TestBox1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestBox1Slice = prismic.SharedSlice<
  "test_box1",
  TestBox1SliceVariation
>;

/**
 * Default variation for TestBox2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestBox2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TestBox2*
 */
type TestBox2SliceVariation = TestBox2SliceDefault;

/**
 * TestBox2 Shared Slice
 *
 * - **API ID**: `test_box2`
 * - **Description**: TestBox2
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestBox2Slice = prismic.SharedSlice<
  "test_box2",
  TestBox2SliceVariation
>;

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Default variation for TextDogBlue Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextDogBlueSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TextDogBlue*
 */
type TextDogBlueSliceVariation = TextDogBlueSliceDefault;

/**
 * TextDogBlue Shared Slice
 *
 * - **API ID**: `text_dog_blue`
 * - **Description**: TextDogBlue
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextDogBlueSlice = prismic.SharedSlice<
  "text_dog_blue",
  TextDogBlueSliceVariation
>;

/**
 * Default variation for TheVision Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TheVisionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TheVision*
 */
type TheVisionSliceVariation = TheVisionSliceDefault;

/**
 * TheVision Shared Slice
 *
 * - **API ID**: `the_vision`
 * - **Description**: TheVision
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TheVisionSlice = prismic.SharedSlice<
  "the_vision",
  TheVisionSliceVariation
>;

/**
 * Default variation for TitleAskAndAnswer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAskAndAnswerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleAskAndAnswer*
 */
type TitleAskAndAnswerSliceVariation = TitleAskAndAnswerSliceDefault;

/**
 * TitleAskAndAnswer Shared Slice
 *
 * - **API ID**: `title_ask_and_answer`
 * - **Description**: TitleAskAndAnswer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAskAndAnswerSlice = prismic.SharedSlice<
  "title_ask_and_answer",
  TitleAskAndAnswerSliceVariation
>;

/**
 * Default variation for TitleBenefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleBenefits*
 */
type TitleBenefitsSliceVariation = TitleBenefitsSliceDefault;

/**
 * TitleBenefits Shared Slice
 *
 * - **API ID**: `title_benefits`
 * - **Description**: TitleBenefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBenefitsSlice = prismic.SharedSlice<
  "title_benefits",
  TitleBenefitsSliceVariation
>;

/**
 * Default variation for TitleCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleCard*
 */
type TitleCardSliceVariation = TitleCardSliceDefault;

/**
 * TitleCard Shared Slice
 *
 * - **API ID**: `title_card`
 * - **Description**: TitleCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleCardSlice = prismic.SharedSlice<
  "title_card",
  TitleCardSliceVariation
>;

/**
 * Default variation for TitleComplex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleComplexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleComplex*
 */
type TitleComplexSliceVariation = TitleComplexSliceDefault;

/**
 * TitleComplex Shared Slice
 *
 * - **API ID**: `title_complex`
 * - **Description**: TitleComplex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleComplexSlice = prismic.SharedSlice<
  "title_complex",
  TitleComplexSliceVariation
>;

/**
 * Default variation for TitleConnecting Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleConnectingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleConnecting*
 */
type TitleConnectingSliceVariation = TitleConnectingSliceDefault;

/**
 * TitleConnecting Shared Slice
 *
 * - **API ID**: `title_connecting`
 * - **Description**: TitleConnecting
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleConnectingSlice = prismic.SharedSlice<
  "title_connecting",
  TitleConnectingSliceVariation
>;

/**
 * Default variation for TitleCoreEcosystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleCoreEcosystemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleCoreEcosystem*
 */
type TitleCoreEcosystemSliceVariation = TitleCoreEcosystemSliceDefault;

/**
 * TitleCoreEcosystem Shared Slice
 *
 * - **API ID**: `title_core_ecosystem`
 * - **Description**: TitleCoreEcosystem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleCoreEcosystemSlice = prismic.SharedSlice<
  "title_core_ecosystem",
  TitleCoreEcosystemSliceVariation
>;

/**
 * Default variation for TitleCoreFunctions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleCoreFunctionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleCoreFunctions*
 */
type TitleCoreFunctionsSliceVariation = TitleCoreFunctionsSliceDefault;

/**
 * TitleCoreFunctions Shared Slice
 *
 * - **API ID**: `title_core_functions`
 * - **Description**: TitleCoreFunctions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleCoreFunctionsSlice = prismic.SharedSlice<
  "title_core_functions",
  TitleCoreFunctionsSliceVariation
>;

/**
 * Default variation for TitleHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleHeader*
 */
type TitleHeaderSliceVariation = TitleHeaderSliceDefault;

/**
 * TitleHeader Shared Slice
 *
 * - **API ID**: `title_header`
 * - **Description**: TitleHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleHeaderSlice = prismic.SharedSlice<
  "title_header",
  TitleHeaderSliceVariation
>;

/**
 * Default variation for TitleHeaderGradient Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleHeaderGradientSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleHeaderGradient*
 */
type TitleHeaderGradientSliceVariation = TitleHeaderGradientSliceDefault;

/**
 * TitleHeaderGradient Shared Slice
 *
 * - **API ID**: `title_header_gradient`
 * - **Description**: TitleHeaderGradient
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleHeaderGradientSlice = prismic.SharedSlice<
  "title_header_gradient",
  TitleHeaderGradientSliceVariation
>;

/**
 * Default variation for TitleMembership Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMembershipSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleMembership*
 */
type TitleMembershipSliceVariation = TitleMembershipSliceDefault;

/**
 * TitleMembership Shared Slice
 *
 * - **API ID**: `title_membership`
 * - **Description**: TitleMembership
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMembershipSlice = prismic.SharedSlice<
  "title_membership",
  TitleMembershipSliceVariation
>;

/**
 * Default variation for TitleMenuStart Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMenuStartSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleMenuStart*
 */
type TitleMenuStartSliceVariation = TitleMenuStartSliceDefault;

/**
 * TitleMenuStart Shared Slice
 *
 * - **API ID**: `title_menu_start`
 * - **Description**: TitleMenuStart
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMenuStartSlice = prismic.SharedSlice<
  "title_menu_start",
  TitleMenuStartSliceVariation
>;

/**
 * Default variation for TitleMultichain Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMultichainSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleMultichain*
 */
type TitleMultichainSliceVariation = TitleMultichainSliceDefault;

/**
 * TitleMultichain Shared Slice
 *
 * - **API ID**: `title_multichain`
 * - **Description**: TitleMultichain
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleMultichainSlice = prismic.SharedSlice<
  "title_multichain",
  TitleMultichainSliceVariation
>;

/**
 * Default variation for TitlePaymentEcosystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitlePaymentEcosystemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitlePaymentEcosystem*
 */
type TitlePaymentEcosystemSliceVariation = TitlePaymentEcosystemSliceDefault;

/**
 * TitlePaymentEcosystem Shared Slice
 *
 * - **API ID**: `title_payment_ecosystem`
 * - **Description**: TitlePaymentEcosystem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitlePaymentEcosystemSlice = prismic.SharedSlice<
  "title_payment_ecosystem",
  TitlePaymentEcosystemSliceVariation
>;

/**
 * Default variation for TitleSmartProgram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSmartProgramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleSmartProgram*
 */
type TitleSmartProgramSliceVariation = TitleSmartProgramSliceDefault;

/**
 * TitleSmartProgram Shared Slice
 *
 * - **API ID**: `title_smart_program`
 * - **Description**: TitleSmartProgram
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSmartProgramSlice = prismic.SharedSlice<
  "title_smart_program",
  TitleSmartProgramSliceVariation
>;

/**
 * Default variation for TitleSynergy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSynergySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleSynergy*
 */
type TitleSynergySliceVariation = TitleSynergySliceDefault;

/**
 * TitleSynergy Shared Slice
 *
 * - **API ID**: `title_synergy`
 * - **Description**: TitleSynergy
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSynergySlice = prismic.SharedSlice<
  "title_synergy",
  TitleSynergySliceVariation
>;

/**
 * Default variation for TitleTokenUtility Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleTokenUtilitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleTokenUtility*
 */
type TitleTokenUtilitySliceVariation = TitleTokenUtilitySliceDefault;

/**
 * TitleTokenUtility Shared Slice
 *
 * - **API ID**: `title_token_utility`
 * - **Description**: TitleTokenUtility
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleTokenUtilitySlice = prismic.SharedSlice<
  "title_token_utility",
  TitleTokenUtilitySliceVariation
>;

/**
 * Default variation for TitleTokenomics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleTokenomicsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TitleTokenomics*
 */
type TitleTokenomicsSliceVariation = TitleTokenomicsSliceDefault;

/**
 * TitleTokenomics Shared Slice
 *
 * - **API ID**: `title_tokenomics`
 * - **Description**: TitleTokenomics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleTokenomicsSlice = prismic.SharedSlice<
  "title_tokenomics",
  TitleTokenomicsSliceVariation
>;

/**
 * Default variation for TokenWhitepaper Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TokenWhitepaperSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TokenWhitepaper*
 */
type TokenWhitepaperSliceVariation = TokenWhitepaperSliceDefault;

/**
 * TokenWhitepaper Shared Slice
 *
 * - **API ID**: `token_whitepaper`
 * - **Description**: TokenWhitepaper
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TokenWhitepaperSlice = prismic.SharedSlice<
  "token_whitepaper",
  TokenWhitepaperSliceVariation
>;

/**
 * Default variation for TopExchange Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopExchangeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TopExchange*
 */
type TopExchangeSliceVariation = TopExchangeSliceDefault;

/**
 * TopExchange Shared Slice
 *
 * - **API ID**: `top_exchange`
 * - **Description**: TopExchange
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopExchangeSlice = prismic.SharedSlice<
  "top_exchange",
  TopExchangeSliceVariation
>;

/**
 * Default variation for VerticalSteps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VerticalStepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *VerticalSteps*
 */
type VerticalStepsSliceVariation = VerticalStepsSliceDefault;

/**
 * VerticalSteps Shared Slice
 *
 * - **API ID**: `vertical_steps`
 * - **Description**: VerticalSteps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VerticalStepsSlice = prismic.SharedSlice<
  "vertical_steps",
  VerticalStepsSliceVariation
>;

/**
 * Default variation for VisionCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *VisionCard*
 */
type VisionCardSliceVariation = VisionCardSliceDefault;

/**
 * VisionCard Shared Slice
 *
 * - **API ID**: `vision_card`
 * - **Description**: VisionCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionCardSlice = prismic.SharedSlice<
  "vision_card",
  VisionCardSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutTbkFoundationSlice,
      AboutTbkFoundationSliceVariation,
      AboutTbkFoundationSliceDefault,
      BackgroundSlice,
      BackgroundSliceVariation,
      BackgroundSliceDefault,
      BannerAboutSlice,
      BannerAboutSliceVariation,
      BannerAboutSliceDefault,
      BannerIntroSlice,
      BannerIntroSliceVariation,
      BannerIntroSliceDefault,
      BannerVideoSlice,
      BannerVideoSliceVariation,
      BannerVideoSliceDefault,
      BlockchainAndAiBenefitsSlice,
      BlockchainAndAiBenefitsSliceVariation,
      BlockchainAndAiBenefitsSliceDefault,
      BtnReadmoreSlice,
      BtnReadmoreSliceVariation,
      BtnReadmoreSliceDefault,
      ButtonSlice,
      ButtonSliceVariation,
      ButtonSliceDefault,
      CardGroupBenefitsSlice,
      CardGroupBenefitsSliceVariation,
      CardGroupBenefitsSliceDefault,
      CardGroupConnectingSlice,
      CardGroupConnectingSliceVariation,
      CardGroupConnectingSliceDefault,
      CardGroupCoreEcosytemSlice,
      CardGroupCoreEcosytemSliceVariation,
      CardGroupCoreEcosytemSliceDefault,
      CardGroupCoreFunctionsSlice,
      CardGroupCoreFunctionsSliceVariation,
      CardGroupCoreFunctionsSliceDefault,
      CardGroupMultichainSlice,
      CardGroupMultichainSliceVariation,
      CardGroupMultichainSliceDefault,
      CardGroupPaymentEcosystemSlice,
      CardGroupPaymentEcosystemSliceVariation,
      CardGroupPaymentEcosystemSliceDefault,
      CardGroupSynergySlice,
      CardGroupSynergySliceVariation,
      CardGroupSynergySliceDefault,
      CardGroupTokenUtilitySlice,
      CardGroupTokenUtilitySliceVariation,
      CardGroupTokenUtilitySliceDefault,
      CardInitialListingPriceSlice,
      CardInitialListingPriceSliceVariation,
      CardInitialListingPriceSliceDefault,
      CardServicesSlice,
      CardServicesSliceVariation,
      CardServicesSliceDefault,
      CardStatisticSlice,
      CardStatisticSliceVariation,
      CardStatisticSliceDefault,
      CardSynergySlice,
      CardSynergySliceVariation,
      CardSynergySliceDefault,
      CardTokenomicsSlice,
      CardTokenomicsSliceVariation,
      CardTokenomicsSliceDefault,
      CardTotalSupplySlice,
      CardTotalSupplySliceVariation,
      CardTotalSupplySliceDefault,
      ChallengesSlice,
      ChallengesSliceVariation,
      ChallengesSliceDefault,
      CollapeGroupAskAndAnswerSlice,
      CollapeGroupAskAndAnswerSliceVariation,
      CollapeGroupAskAndAnswerSliceDefault,
      CollapseAskedAnsweredSlice,
      CollapseAskedAnsweredSliceVariation,
      CollapseAskedAnsweredSliceDefault,
      ContentSmartProgramSlice,
      ContentSmartProgramSliceVariation,
      ContentSmartProgramSliceDefault,
      CoreTechnologySlice,
      CoreTechnologySliceVariation,
      CoreTechnologySliceDefault,
      CoreValuesSlice,
      CoreValuesSliceVariation,
      CoreValuesSliceDefault,
      CtaSlice,
      CtaSliceVariation,
      CtaSliceDefault,
      DiscriptionSlice,
      DiscriptionSliceVariation,
      DiscriptionSliceDefault,
      EarnSlice,
      EarnSliceVariation,
      EarnSliceDefault,
      ExchangesSlice,
      ExchangesSliceVariation,
      ExchangesSliceDefault,
      FlowEarnSlice,
      FlowEarnSliceVariation,
      FlowEarnSliceDefault,
      FlowEarnMobileCompoSlice,
      FlowEarnMobileCompoSliceVariation,
      FlowEarnMobileCompoSliceDefault,
      FunctionsSlice,
      FunctionsSliceVariation,
      FunctionsSliceDefault,
      HomeCtaMobileSlice,
      HomeCtaMobileSliceVariation,
      HomeCtaMobileSliceDefault,
      IconSlice,
      IconSliceVariation,
      IconSliceDefault,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageEndGridSlice,
      ImageEndGridSliceVariation,
      ImageEndGridSliceDefault,
      ImageStartGridSlice,
      ImageStartGridSliceVariation,
      ImageStartGridSliceDefault,
      ImgBgBenefitsSlice,
      ImgBgBenefitsSliceVariation,
      ImgBgBenefitsSliceDefault,
      ImgBgSmartProgramSlice,
      ImgBgSmartProgramSliceVariation,
      ImgBgSmartProgramSliceDefault,
      ImgBgSynergySlice,
      ImgBgSynergySliceVariation,
      ImgBgSynergySliceDefault,
      ImgBgTokenUtilitySlice,
      ImgBgTokenUtilitySliceVariation,
      ImgBgTokenUtilitySliceDefault,
      IntroductionSlice,
      IntroductionSliceVariation,
      IntroductionSliceDefault,
      JoinOutCommunitySlice,
      JoinOutCommunitySliceVariation,
      JoinOutCommunitySliceDefault,
      LinkSlice,
      LinkSliceVariation,
      LinkSliceDefault,
      LongTermGoalsSlice,
      LongTermGoalsSliceVariation,
      LongTermGoalsSliceDefault,
      MenuWhitePaperSlice,
      MenuWhitePaperSliceVariation,
      MenuWhitePaperSliceDefault,
      MissionCardSlice,
      MissionCardSliceVariation,
      MissionCardSliceDefault,
      MonacoSlice,
      MonacoSliceVariation,
      MonacoSliceDefault,
      NumberStatisticSlice,
      NumberStatisticSliceVariation,
      NumberStatisticSliceDefault,
      OverviewTokenomicsSlice,
      OverviewTokenomicsSliceVariation,
      OverviewTokenomicsSliceDefault,
      PaymentEcosystemSlice,
      PaymentEcosystemSliceVariation,
      PaymentEcosystemSliceDefault,
      PieChartSlice,
      PieChartSliceVariation,
      PieChartSliceDefault,
      PieChartTokenomicsSlice,
      PieChartTokenomicsSliceVariation,
      PieChartTokenomicsSliceDefault,
      PurposeCardSlice,
      PurposeCardSliceVariation,
      PurposeCardSliceDefault,
      ReadyToTransformSlice,
      ReadyToTransformSliceVariation,
      ReadyToTransformSliceDefault,
      ServiceSlice,
      ServiceSliceVariation,
      ServiceSliceDefault,
      SliceInifitySlice,
      SliceInifitySliceVariation,
      SliceInifitySliceDefault,
      SliderTokenSlice,
      SliderTokenSliceVariation,
      SliderTokenSliceDefault,
      StepApplySlice,
      StepApplySliceVariation,
      StepApplySliceDefault,
      SustainabilityInitiativesSlice,
      SustainabilityInitiativesSliceVariation,
      SustainabilityInitiativesSliceDefault,
      TableEarnSlice,
      TableEarnSliceVariation,
      TableEarnSliceDefault,
      TableMembershipSlice,
      TableMembershipSliceVariation,
      TableMembershipSliceDefault,
      TableMembershipPerksSlice,
      TableMembershipPerksSliceVariation,
      TableMembershipPerksSliceDefault,
      TableMultiTiredSlice,
      TableMultiTiredSliceVariation,
      TableMultiTiredSliceDefault,
      TbkEcosystemSlice,
      TbkEcosystemSliceVariation,
      TbkEcosystemSliceDefault,
      TbkFoundationBackgroundSlice,
      TbkFoundationBackgroundSliceVariation,
      TbkFoundationBackgroundSliceDefault,
      TbkIdentifySlice,
      TbkIdentifySliceVariation,
      TbkIdentifySliceDefault,
      TbkIdentifyAbassadorSlice,
      TbkIdentifyAbassadorSliceVariation,
      TbkIdentifyAbassadorSliceDefault,
      TbkIdentifyGiftSlice,
      TbkIdentifyGiftSliceVariation,
      TbkIdentifyGiftSliceDefault,
      TbkIdentifyReferralSlice,
      TbkIdentifyReferralSliceVariation,
      TbkIdentifyReferralSliceDefault,
      TbkSmartProgramSlice,
      TbkSmartProgramSliceVariation,
      TbkSmartProgramSliceDefault,
      TbkTokenEcosystemSlice,
      TbkTokenEcosystemSliceVariation,
      TbkTokenEcosystemSliceDefault,
      TestBox1Slice,
      TestBox1SliceVariation,
      TestBox1SliceDefault,
      TestBox2Slice,
      TestBox2SliceVariation,
      TestBox2SliceDefault,
      TextSlice,
      TextSliceVariation,
      TextSliceDefault,
      TextDogBlueSlice,
      TextDogBlueSliceVariation,
      TextDogBlueSliceDefault,
      TheVisionSlice,
      TheVisionSliceVariation,
      TheVisionSliceDefault,
      TitleAskAndAnswerSlice,
      TitleAskAndAnswerSliceVariation,
      TitleAskAndAnswerSliceDefault,
      TitleBenefitsSlice,
      TitleBenefitsSliceVariation,
      TitleBenefitsSliceDefault,
      TitleCardSlice,
      TitleCardSliceVariation,
      TitleCardSliceDefault,
      TitleComplexSlice,
      TitleComplexSliceVariation,
      TitleComplexSliceDefault,
      TitleConnectingSlice,
      TitleConnectingSliceVariation,
      TitleConnectingSliceDefault,
      TitleCoreEcosystemSlice,
      TitleCoreEcosystemSliceVariation,
      TitleCoreEcosystemSliceDefault,
      TitleCoreFunctionsSlice,
      TitleCoreFunctionsSliceVariation,
      TitleCoreFunctionsSliceDefault,
      TitleHeaderSlice,
      TitleHeaderSliceVariation,
      TitleHeaderSliceDefault,
      TitleHeaderGradientSlice,
      TitleHeaderGradientSliceVariation,
      TitleHeaderGradientSliceDefault,
      TitleMembershipSlice,
      TitleMembershipSliceVariation,
      TitleMembershipSliceDefault,
      TitleMenuStartSlice,
      TitleMenuStartSliceVariation,
      TitleMenuStartSliceDefault,
      TitleMultichainSlice,
      TitleMultichainSliceVariation,
      TitleMultichainSliceDefault,
      TitlePaymentEcosystemSlice,
      TitlePaymentEcosystemSliceVariation,
      TitlePaymentEcosystemSliceDefault,
      TitleSmartProgramSlice,
      TitleSmartProgramSliceVariation,
      TitleSmartProgramSliceDefault,
      TitleSynergySlice,
      TitleSynergySliceVariation,
      TitleSynergySliceDefault,
      TitleTokenUtilitySlice,
      TitleTokenUtilitySliceVariation,
      TitleTokenUtilitySliceDefault,
      TitleTokenomicsSlice,
      TitleTokenomicsSliceVariation,
      TitleTokenomicsSliceDefault,
      TokenWhitepaperSlice,
      TokenWhitepaperSliceVariation,
      TokenWhitepaperSliceDefault,
      TopExchangeSlice,
      TopExchangeSliceVariation,
      TopExchangeSliceDefault,
      VerticalStepsSlice,
      VerticalStepsSliceVariation,
      VerticalStepsSliceDefault,
      VisionCardSlice,
      VisionCardSliceVariation,
      VisionCardSliceDefault,
    };
  }
}
