// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  background: dynamic(() => import("./Background")),
  banner_video: dynamic(() => import("./BannerVideo")),
  button: dynamic(() => import("./Button")),
  discription: dynamic(() => import("./Discription")),
  icon: dynamic(() => import("./Icon")),
  image: dynamic(() => import("./Image")),
  link: dynamic(() => import("./Link")),
  text: dynamic(() => import("./Text")),
  title_complex: dynamic(() => import("./TitleComplex")),
  title_header: dynamic(() => import("./TitleHeader")),
  title_header_gradient: dynamic(() => import("./TitleHeaderGradient")),
};
